Test tests.

diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -1,50 +1,216 @@
 #!/bin/sh
+
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
 #
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
+# This hook is called with the following parameters:
 #
-# To enable this hook, rename this file to "pre-commit".
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
+remote="$1"
+url="$2"
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --bool hooks.allownonascii)
+z40=0000000000000000000000000000000000000000
 
-# Redirect output to stderr.
-exec 1>&2
+while read local_ref local_sha remote_ref remote_sha
+do
+        if [ "$local_sha" = $z40 ]
+        then
+                # Handle delete
+                :
+        else
+                if [ "$remote_sha" = $z40 ]
+                then
+                        # New branch, examine all commits
+                        range="$local_sha"
+                else
+                        # Update to existing branch, examine new commits
+                        range="$remote_sha..$local_sha"
+                fi
 
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
+                # Check for WIP commit
+                commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+                if [ -n "$commit" ]
+                then
+                        echo >&2 "Found WIP commit in $local_ref, not pushing"
+                        exit 1
+                fi
+        fi
+done
 
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-bookFilterType=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
+exit 0
+patrycja@patrycja-OptiPlex-7020:~/Kod/robot/.git/hooks$ cat pre-push.sample
+#!/bin/sh
 
-This can cause problems if you want to work with people on other platforms.
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
+#
+# This hook is called with the following parameters:
+#
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
 
-To be portable it is advisable to rename the file.
+remote="$1"
+url="$2"
 
-If you know what you are doing you can disable this check using:
+z40=0000000000000000000000000000000000000000
 
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
+while read local_ref local_sha remote_ref remote_sha
+do
+        if [ "$local_sha" = $z40 ]
+        then
+                # Handle delete
+                :
+        else
+                if [ "$remote_sha" = $z40 ]
+                then
+                        # New branch, examine all commits
+                        range="$local_sha"
+                else
+                        # Update to existing branch, examine new commits
+                        range="$remote_sha..$local_sha"
+                fi
+
+                # Check for WIP commit
+                commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+                if [ -n "$commit" ]
+                then
+                        echo >&2 "Found WIP commit in $local_ref, not pushing"
+                        exit 1
+                fi
+        fi
+done
+
+exit 0
+patrycja@patrycja-OptiPlex-7020:~/Kod/robot/.git/hooks$ cat pre-push.sample
+#!/bin/sh
+
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
+#
+# This hook is called with the following parameters:
+#
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
+
+remote="$1"
+url="$2"
+
+z40=0000000000000000000000000000000000000000
+
+while read local_ref local_sha remote_ref remote_sha
+do
+        if [ "$local_sha" = $z40 ]
+        then
+                # Handle delete
+                :
+        else
+                if [ "$remote_sha" = $z40 ]
+                then
+                        # New branch, examine all commits
+                        range="$local_sha"
+                else
+                        # Update to existing branch, examine new commits
+                        range="$remote_sha..$local_sha"
+                fi
+
+                # Check for WIP commit
+                commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+                if [ -n "$commit" ]
+                then
+                        echo >&2 "Found WIP commit in $local_ref, not pushing"
+                        exit 1
+                fi
+        fi
+done
+
+exit 0
+patrycja@patrycja-OptiPlex-7020:~/Kod/robot/.git/hooks$ cat pre-push.sample
+#!/bin/sh
+
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
+#
+# This hook is called with the following parameters:
+#
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
+
+remote="$1"
+url="$2"
+
+z40=0000000000000000000000000000000000000000
+
+while read local_ref local_sha remote_ref remote_sha
+do
+        if [ "$local_sha" = $z40 ]
+        then
+                # Handle delete
+                :
+        else
+                if [ "$remote_sha" = $z40 ]
+                then
+                        # New branch, examine all commits
+                        range="$local_sha"
+                else
+                        # Update to existing branch, examine new commits
+                        range="$remote_sha..$local_sha"
+                fi
+
+                # Check for WIP commit
+                commit=`git rev-list -n 1 --grep '^WIP' "$range"`
+                if [ -n "$commit" ]
+                then
+                        echo >&2 "Found WIP commit in $local_ref, not pushing"
+                        exit 1
+                fi
+        fi
+done
 
 # Prevent git commit if mvn package fail
 echo "Running tests..."
@@ -52,10 +218,8 @@ echo "Running tests..."
 if  mvn clean test -q
 then
 	echo "Tests passed."
+	exit 0
 else
 	echo "Tests failed"
 	exit 1
 fi
-
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
